{% set name = "data-quality-control" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/data_quality_control-{{ version }}.tar.gz
  sha256: 27f0a54b73afe4afca15546528f6ebf424f3edf0954d22b2ac2e2fac145ffd36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - ipykernel >=6.17.1,<7.0.0
    - pandas >=1.5.1,<2.0.0
    - matplotlib-base >=3.6.2,<4.0.0
    - circle-fit >=0.1.3,<0.2.0
    - plotly >=5.11.0,<6.0.0
    - spyder 5.4
    - requests >=2.28.1,<3.0.0
    - numpy >=1.23.4,<2.0.0
    - suds >=1.1.2,<2.0.0
    - sqlalchemy >=1.4.43,<2.0.0
    - glob2 >=0.7.0,<0.8.0
    - aiohttp >=3.8.3,<4.0.0
    - spyder-kernels 2.4.*
    - mat73 >=0.59.0,<0.60.0
    - cdsapi >=0.5.1,<0.6.0
    - xarray >=2022.11.0,<2023.0.0
    - pytest

test:
  imports:
    - fun
    - src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashimgiyanani/data_quality_control
  summary: Python code to perform data quality control on wind energy data, especially meteorological data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ashimgiyanani
